name: Nuyul Contributions

on:
  schedule:
    - cron: "0 */6 * * *"  # jalan setiap 6 jam
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Buat commit kosong
        run: |
          date > dummy.txt
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "chore: auto update $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
