name: Nuyul Contributions

on:
  schedule:
    - cron: "0 * * * *"    # Setiap jam
    - cron: "0 0 * * *"    # Setiap hari jam 00:00 UTC
  workflow_dispatch:       # Untuk run manual

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Git config
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      # Bagian buat file dummy kalau dijalankan manual atau setiap jam
      - name: Buat dummy file
        if: |
          github.event_name == 'workflow_dispatch' || github.event.schedule == '0 * * * *'
        run: |
          mkdir -p files
          echo "$(date)" > "files/dummy-$(date +%s).txt"
          git add files/
          git commit -m "update: $(date)" || echo "No changes to commit"
          git push

      # Bagian bersihkan file hanya saat jadwal bersih harian
      - name: Bersihkan file sampah
        if: github.event.schedule == '0 0 * * *'
        run: |
          git rm -rf files/*
          git commit -m "auto-cleanup: $(date)" || echo "Nothing to clean"
          git push
