name: Nuyul Contributions

on:
  schedule:
    # Setiap 1 jam sekali
    - cron: "0 * * * *"
    # Pembersihan sekali sehari, jam 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Git config
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Tambahkan file dummy setiap 1 jam
        if: ${{ github.event.schedule == '0 * * * *' }}
        run: |
          mkdir -p files
          echo "$(date)" > "files/dummy-$(date +%s).txt"
          git add files/
          git commit -m "update dummy file: $(date)" || echo "No changes to commit"
          git push

      - name: Bersihkan file dummy setiap hari jam 00:00 UTC
        if: ${{ github.event.schedule == '0 0 * * *' }}
        run: |
          rm -rf files/*
          git add -u
          git commit -m "auto-cleanup files: $(date)" || echo "Nothing to clean"
          git push
