name: Nuyul Contributions

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Buat dummy file
        run: |
          date > dummy.txt
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add dummy.txt
          git commit -m "update: $(date)" || echo "No changes to commit"
          git push
